version: 2.1
workflows:
    build-and-deploy-lumos-fe:
        jobs:
            - buildAndDeploy
jobs:
    buildAndDeploy:
        environment:
            GENERATE_SOURCEMAP: false
        docker:
            - image: "circleci/node"
        steps:
            - checkout
            - run:
                  name: Check node version
                  command: |
                      node -v
                      npm -v
                      yarn -v
            - restore_cache:
                  key: yarn-cache
            - run:
                  name: Install dependencies
                  command: yarn
            - save_cache:
                paths: yarn-cache
                key: yarn-cache-{{ epoch }}
            - run:
                  name: build
                  command: yarn build
            - run:
                name: Scan ssh key
                command: ssh-keyscan $BACKEND_HOST >> ~/.ssh/known_hosts
            - add_ssh_keys:
                fingerprints:
                    - de:22:0e:e0:2a:5e:99:d2:bd:49:62:d8:f7:ba:4b:3a
            - run:
                name: Install rsync
                command: sudo apt-get install rsync -y
            - run:
                name: Deploy
                command: |
                    rsync -avz -e "ssh -p $PORT -o StrictHostKeyChecking=no" --delete ./build/* root@$BACKEND_HOST:$LUMOS_DIR 2>&1 
